### ISSUE TITLE
getting this error upon gradle build: Could not get unknown property 'OXFORD_APP_ID'

### ISSUE THREAD

**Issue by princeofori** [jivimberg/PracticePronunciation#3]
Could not get unknown property 'OXFORD_APP_ID' for ProductFlavor_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=17, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=25, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=10, versionName=1.7, applicationId=com.eightblocksaway.android.practicepronunciation, testApplicationId=null, testInstrumentationRunner=android.support.test.runner.AndroidJUnitRunner, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.ProductFlavor.
Open File

**Comment by jivimberg** [comment]
Hi! I think the reason for that is that I didn't published the OXFORD_APP_ID on github. You can get your own app ID for free here: https://developer.oxforddictionaries.com/ to run the app. Hope this helps!
